# Generated by Django 5.0.4 on 2024-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_category_customuser_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_block',
            field=models.BooleanField(default=True),
        ),
    ]
